id: D472EF362
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:17:37+00:00'
last_modified: '2022-05-27T09:42:25.431894+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '8576':
      image_group_id: I1PD95903
      title: དབུ་མའི་དོན་བསྡུས་པ།
      total_pages: 1649
      order: 58
      base_file: 8576.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
