id: 66ceff3c733f42a89cb71b718c7f8a5e
initial_creation_type: ocr
source_metadata:
  volumes:
    012ebd2cb3b340c49f9ec9d7f3c66927:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: ''
      total_pages: 1649
      volume_number: 58
